title: Bruke Baraki
description: Portfolio Website
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Custom includes
include:
  - _includes/head-custom.html

header_links:
- title: Home
  url: /
- title: Resume
  url: /resume/
- title: Research
  url: /#research
